# Generated by Django 3.0.4 on 2020-03-11 07:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.CharField(max_length=255)),
                ('char_key', models.CharField(max_length=255)),
                ('char_name', models.CharField(max_length=255, unique=True)),
                ('json_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('craeted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
